### ISSUE TITLE
Examples do not run

### ISSUE THREAD

**Issue by Neuroplant** [Reinbert/pca9685#1]
Hello, 
most of the example programms do not run because wiringPi is not initialisied

Neuroplant

**Comment by cst0** [comment]
@Reinbert Seconding this issue. With WiringPi properly installed, running `make servo` works and produces the `servo` executable. When the `servo` executable is run (with sudo, as the user does not have the required permissions), the following error appears:

```
pwmWrite: You have not called one of the wiringPiSetup
    functions, so I'm aborting your program before it crashes anyway.
```

This issue was tested with and exists for `calibrate` and `leds`, but not `piezo`, which is interesting. I will debug and report back soon.

**Comment by Reinbert** [comment]
Thank you for your feedback. They probably changed the way wiring pi is initialized. I'll look into it.

**Comment by Reinbert** [comment]
I just updated the examples by adding the call to the wiringPiSetup() function. They should now run again. Here's the [commit](https://github.com/Reinbert/pca9685/tree/1f193f12e47513c55a895c48486b1a153d45aa64).
-> Closing
